/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tcurt.javasandbox.commonwords;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.List;

import org.assertj.core.util.Arrays;
import org.junit.Test;

public class SolutionTest {

    private StreamSolution streamSolution = new StreamSolution();
    private TreeMapSolution treeMapSolution = new TreeMapSolution();

    @Test
    public void testFull() {
        String test = "A test that we did a good test. Did we? We are happy.";
        String[] expected = Arrays.array("we", "a", "test", "did", "that");

        List<String> actualStream = streamSolution.mostCommonWords(test, 5);
        assertThat(actualStream).contains(expected);

        List<String> actualTreeMap = treeMapSolution.mostCommonWords(test, 5);
        assertThat(actualTreeMap).contains(expected);
    }
}
